// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TodoXaml.TodoServiceApi.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Priority.
    /// </summary>
    public static class Priority
    {
        public const string High = "High";
        public const string Normal = "Normal";
        public const string Low = "Low";
    }
}
